name: Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0
          variable_files: |
            vars.tfvars
      - name: Set environment variables
        id: set_env
        run: |
          echo "::set-env name=ETL-BUCKET-NAME::$(cat terraform/vars.tfvars | grep etl-bucket-name | cut -d '=' -f 2 | tr -d ' ')"
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init -backend-config=prod_config.tfvars
      - name: Plan
        working-directory: terraform/
        id: plan
        run: terraform plan -var-file="vars.tfvars"
      - name: Apply
        working-directory: terraform/
        run: terraform apply -var-file="vars.tfvars" -auto-approve
      - name: Sync files to S3
        run: aws s3 sync . s3://${{ env.ETL-BUCKET-NAME }}
