name: Main

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0
    - name: Plan
      run: terraform plan
    - name: Apply
      if: success()
      run: terraform apply -auto-approve
    - name: Upload to S3
      if: success()
      uses: aws-actions/s3-upload-action@v1
      with:
        bucket: ingridy-data-etl
        local_dir: .
        prefix: code/
        acl: public-read
