name: Main

on:
  push:
    branches: [ main ]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      depends_on: Configure AWS credentials
      with:
        terraform_version: 0.15.0
    - name: Plan
      depends_on: Install Terraform
      run: terraform plan
    - name: Apply
      depends_on: Plan
      run: terraform apply -auto-approve
    - name: Upload to S3
      depends_on: Apply
      uses: aws-actions/s3-upload-action@v1
      with:
        bucket: ingridy-data-etl
        local_dir: .
        prefix: code/
        acl: public-read
