name: Main

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-2
      # - name: Install Terraform
      #   uses: hashicorp/setup-terraform@v1
      # - name: Terraform Init
      #   working-directory: terraform/
      #   run: terraform init -backend-config=prod_config.tfvars
      # - name: Plan
      #   working-directory: terraform/
      #   run: terraform plan -var-file="vars.tfvars"
      # - name: Apply
      #   working-directory: terraform/
      #   run: terraform apply -var-file="vars.tfvars" -auto-approve
      # - name: Set environment variables
      #   run: |
      #     echo "ETL_BUCKET_NAME=$(cat terraform/vars.tfvars | grep etl-bucket-name | cut -d '=' -f 2 | tr -d ' ')" >> $GITHUB_ENV
      
      - name: check modified files
        id: check-modified-files
        run: |
          CHANGED_FILES=$(git show HEAD --name-only --diff-filter=ACM)
          if [[ $CHANGED_FILES =~ "terraform" ]]; then
            echo "IS_MODIFIED = 1"
          else
            echo "IS_MODIFIED = 0"
          fi
      - name: Sync files to S3
        if: ${{ env.IS_MODIFIED == 1 }}
        run: aws s3 sync . s3://${{ env.ETL_BUCKET_NAME }}/code/
